<?php
/**
 * @file
 * Install, update and uninstall functions for the minimal installation profile.
 */

function config_deploy_install() {
  $file_storage = new \Drupal\Core\Config\FileStorage(drupal_get_path('profile', 'config_deploy'));

  $system_site = $file_storage->read('system.site');
  if (isset($system_site['uuid'])) {
    \Drupal::configFactory()
      ->getEditable('system.site')
      ->set('uuid', $system_site['uuid'])
      ->save();
  }
}
